# Generated by Django 3.2.4 on 2023-01-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_stocklist_coindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindata',
            name='coin_volume',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
