# Generated by Django 3.2.4 on 2023-01-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_coindata_coin_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindata',
            name='coin_volume',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
