# Generated by Django 3.2.4 on 2023-01-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_coindata_coin_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindata',
            name='coin_1h_per',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coindata',
            name='coin_24h_per',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coindata',
            name='coin_7d_per',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coindata',
            name='coin_circulating_supply',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coindata',
            name='coin_mkt_cap',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
