# Generated by Django 3.2.4 on 2023-01-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20230112_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coindata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coindata',
            name='updated_at',
        ),
    ]
